# Generated by Django 3.2.3 on 2026-02-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=50)),
                ('sku_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('receive_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receive_currency', models.CharField(max_length=10)),
                ('send_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('send_currency', models.CharField(max_length=10)),
                ('commission_rate', models.FloatField()),
                ('region_code', models.CharField(max_length=10)),
                ('validity', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
